### PR TITLE
Add support for vet.domains

### PR DESCRIPTION
**Pull request by ifavo**
This Pull Requests adds support for name based searches.

- When entering something with a dot (`.`)  a name lookup will be tried.
- If successful, a redirect to the resolved address happens.
- If not successful, a new error message is shown.

I am unsure about the use of connex' `cache` method. Would it be possible to use it?

An example deployment is available on https://insight.vechain.vet

### CODE REVIEW

**Review by akanoce — CHANGES_REQUESTED** [review]
Hey @ifavo , thanks a lot for your PR.
I see you pushed the package-lock.json but we're using yarn as a package manager. Could you remove that file and do a fresh install with yarn? A part from this, LGTM

**Comment by ifavo** [comment]
> Hey @ifavo , thanks a lot for your PR. I see you pushed the package-lock.json but we're using yarn as a package manager. Could you remove that file and do a fresh install with yarn? A part from this, LGTM

@akanoce Thank you for reviewing the PR! I've removed the `package-lock.json`. Because no dependency was added, there is no need to update the `yarn.lock` file.

**Comment by akanoce** [comment]
Thanks @ifavo , any chance we can remove the modified `yarn.lock` as well since no package has changed?

**Comment by ifavo** [comment]
@akanoce Done! I am sorry, was not checking on that, will do that better in the future.

**Review by akanoce — APPROVED** [review]

**Comment by akanoce** [comment]
> @akanoce Done! I am sorry, was not checking on that, will do that better in the future.

No problem at all! PR is approved: feel free to merge it at your own discretion

**Comment by ifavo** [comment]
> > @akanoce Done! I am sorry, was not checking on that, will do that better in the future.
> 
> No problem at all! PR is approved: feel free to merge it at your own discretion

I lack the permission to merge, can you please complete that?

**Comment by libotony** [comment]
> * When entering something with a dot (`.`)  a name lookup will be tried.

@ifavo I wonder the reason for sticking to `.`rather than `.vet`?

**Comment by ifavo** [comment]
@libotony it's because there could be more domains in the future, it supports new names without requiring an update

**Comment by libotony** [comment]
> @libotony it's because there could be more domains in the future, it supports new names without requiring an update

I see, thank you for the explanation.

**Pull request merged**
