### PR TITLE
feat/add-solo

### PR DESCRIPTION
**Pull request by claytonneal**
Added Solo network so can be used as a basic block explorer when developing against Solo

### CODE REVIEW

**Comment by libotony** [comment]
Thanks for the PR, https://www.npmjs.com/package/@vechain/devpal  does this meets your requirement?

**Comment by claytonneal** [comment]
ahh didnt know that existed, lets cancel this PR

**Comment by claytonneal** [comment]
hey @libotony would be great to publish DevPal from a vechain repo and add it to our docs!

**Comment by akanoce** [comment]
@claytonneal @libotony it may makes sense to reopen this pr since it would be useful for local development
Despite devpal being a good tool, it may be difficult to integrate it in certain scenarios (pipelines, ci/cd)...
I'd also offer the possibility to override the solo network url from env variable so we have the possibility to change it when spinned up locally

**Comment by libotony** [comment]
> @claytonneal @libotony it may makes sense to reopen this pr since it would be useful for local development Despite devpal being a good tool, it may be difficult to integrate it in certain scenarios (pipelines, ci/cd)... I'd also offer the possibility to override the solo network url from env variable so we have the possibility to change it when spinned up locally

Could you elaborate on the scenarios? I might consider `devpal` is a good one for local development.

**Comment by akanoce** [comment]
> > @claytonneal @libotony it may makes sense to reopen this pr since it would be useful for local development Despite devpal being a good tool, it may be difficult to integrate it in certain scenarios (pipelines, ci/cd)... I'd also offer the possibility to override the solo network url from env variable so we have the possibility to change it when spinned up locally
> 
> Could you elaborate on the scenarios? I might consider `devpal` is a good one for local development.

The main issue with running devpal in these scenarios, is that it does not run in the background, which is is mandatory for dev/ci pipelines where you run multiple commands. 
As most people are running the solo node via docker, a better alternative would be to publish images for both [insight-app](https://github.com/vechain/insight-app) and [inspector-app](https://github.com/vechain/inspector-app). I already did this for insight, and I could easily do the same for inspector.
This way devs could simply pull the images in the same `docker-compose` file, spinning up everything they need for local development, and devpal would simply become a `docker-compose` file. I see this providing a better DX and also be more mantainable, as docker images are always updated .

**Pull request closed without merging**
