### PR TITLE
Account Events

### LINKED ISSUE #9: Empty account events
There's bunch of events for `0xdb49e701883f08ce77292102de10eb39e31fa1b1` account, but `Events` tab showing only ```No content```.

image

### PR DESCRIPTION
**Pull request by dractw**
resolves #9 with VTHO contracts

### CODE REVIEW

**Comment by qianbin** [comment]
@dractw the `Events` tab under account view only displays events which are emitted by this account.

**Comment by dractw** [comment]
@qianbin So what about the events where account is participating?

**Comment by qianbin** [comment]
> @qianbin So what about the events where account is participating?

There's must be an extra view for such content. Expecting vechainstats.com or the new coming official explorer including it.

**Comment by dractw** [comment]
> > @qianbin So what about the events where account is participating?
> 
> There's must be an extra view for such content. Expecting vechainstats.com or the new coming official explorer including it.

I think there can be such tab as 'VET/VTHO' at `transfers` view,  and why we can't use node directly but explorer?

**Comment by qianbin** [comment]
> > > @qianbin So what about the events where account is participating?
> > 
> > 
> > There's must be an extra view for such content. Expecting vechainstats.com or the new coming official explorer including it.
> 
> I think there can be such tab as 'VET/VTHO' at `transfers` view, and why we can't use node directly but explorer?

VTHO transfer log was already available, you may need reload the page. But for some accounts, it'll be timeout to query, since log db is not well optimized for this case. 

截屏2019-11-0520 18 46

**Comment by dractw** [comment]
> > > > @qianbin So what about the events where account is participating?
> > > 
> > > 
> > > There's must be an extra view for such content. Expecting vechainstats.com or the new coming official explorer including it.
> > 
> > 
> > I think there can be such tab as 'VET/VTHO' at `transfers` view, and why we can't use node directly but explorer?
> 
> VTHO transfer log was already available, you may need reload the page. But for some accounts, it'll be timeout to query, since log db is not well optimized for this case.
> 
> 截屏2019-11-0520 18 46

Yes, i know that already. You probably misunderstood what i'm talking about - im proposing tabs in `Events` view
like tabs in `transfers`, but with `emmiting/participating` events inside.

**Comment by qianbin** [comment]
> Yes, i know that already. You probably misunderstood what i'm talking about - im proposing tabs in `Events` view like tabs in `transfers`, but with `emmiting/participating` events inside.

Oh, sorry. But i think this feature is not suitable for this lightweight app.

**Pull request closed without merging**
